- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Initialize Docker Swarm
  shell: docker swarm init
  ignore_errors: true
