- hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      yum:
        name:
          - docker
          - nginx
          - git
        state: present
        update_cache: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Enable Docker Swarm
      shell: docker swarm init || true

    - name: Create NGINX conf directory (if not exists)
      file:
        path: /etc/nginx/conf.d
        state: directory

    - name: Copy NGINX config
      copy:
        src: ../docker/nginx.conf
        dest: /etc/nginx/conf.d/yii2.conf

    - name: Remove default NGINX welcome config
      file:
        path: /etc/nginx/conf.d/welcome.conf
        state: absent

    - name: Enable and restart NGINX
      systemd:
        name: nginx
        enabled: yes
        state: restarted
