- hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose
        - nginx
        - git

    - name: Enable Docker Swarm
      shell: docker swarm init || true

    - name: Configure NGINX
      copy:
        src: ../docker/nginx.conf
        dest: /etc/nginx/sites-available/yii2
    - name: Enable NGINX config
      file:
        src: /etc/nginx/sites-available/yii2
        dest: /etc/nginx/sites-enabled/yii2
        state: link
        force: yes
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
